name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            pm2 stop ponpub-service-prod
            cd ~/ponpub-demo/service
            git pull
            git status
            rm -rf build
            yarn install
            yarn build
            pm2 restart ponpub-service-prod